# Generated by Django 2.0.8 on 2018-11-11 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UCSDMarket', '0003_auto_20181109_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('canDeliver', models.BooleanField()),
                ('condition', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('contactInformation', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='listingKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UCSDMarket.Listing'),
            preserve_default=False,
        ),
    ]
